_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": usage/completion_tokens
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": _timestamp
              "6": []
              "7": []
            - "1": usage/total_tokens
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": usage/prompt_tokens
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": usage/elapsed_time
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.2
        t:
            "1":
                - 55
                - 95
            "2":
                - 55
                - 95
            "3":
                - 2
                - 7
                - 23
                - 51
                - 55
            "4": 3.11.2
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": darwin-x86_64
